spring:
  profiles:
    active: dev
  config:
    import: optional:dotenv:.env
  main:
    allow-circular-references: true
  application:
    name: usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/practica_final_backend
    username: ${MYSQL_DATABASE_USER}
    password: ${MYSQL_DATABASE_PWD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              # action: create
              action: none
              create-target: schema.sql
      hibernate:
        format_sql: true
  flyway:
    # enabled: true
    enabled: false
    locations: classpath:db/migration
    # baseline-on-migrate: true
    baseline-on-migrate: false
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
